# Generated by Django 4.2.7 on 2024-02-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='datetime_field',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
