# Generated by Django 4.2.10 on 2024-02-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_datetime_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('Situationship', 'Situationship'), ('Officially together', 'Officially together'), ('Engaged', 'Engaged'), ('Married', 'Married')], max_length=20, null=True),
        ),
    ]
